spring:
  datasource:
    url: jdbc:mysql://database-1.ch6w24ckupkt.ap-northeast-2.rds.amazonaws.com:3306/mydb
    username: admin
    password: rlawlgh11
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

aws:
  s3:
    bucket-name: team-project1  # S3 버킷 이름 설정
  cognito:
    region: ap-northeast-2  # Cognito 리전 설정
    user-pool-id: ap-northeast-2_oN4ac76ji
    client-id: 7tir3q8beugnkpq07t4ugce595
